### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by varungu** [varungu/Android-Bootcamp#1]
My app is complete, Please review. /cc @codepathreview @codepath

![readme](https://cloud.githubusercontent.com/assets/2263278/7039227/44dd6ba4-dd73-11e4-98a3-e519a0231e12.gif)

**Comment by varungu** [comment]
![readme](https://cloud.githubusercontent.com/assets/2263278/7039214/2646044e-dd73-11e4-9957-0bdb090f59cd.gif)

**Comment by varungu** [comment]
@codepathreview @codepath
Added code to use SqlLite to persist data. There are 2 issues with it
1. Duplicate values are not allowed since I am using value itself as a primary key
2. List order will change after app restart since and I delete and add another row on edit.

I plan to fix it along with custom adapter.

**Comment by varungu** [comment]
I am confused between just custom adapter view and using RecyclerView. What would be better approach for custom UI? /cc @codepathreview @codepath

**Comment by nesquena** [comment]
The choice is between a ListView with custom adapter and RecyclerView (which requires its own custom recycler adapter). Either is fine but we will be focusing on ListView for earlier classes so probably better to use that for now. We will discuss RecyclerView as well later.

**Comment by nidhi1608** [comment]
What's your full name so I can match you?

**Comment by varungu** [comment]
@nidhi1608 My details are as follows
Name: Varun Gupta
Email: varungupta@box.com

**Comment by varungu** [comment]
Added custom adapter and due date support. Also fixed persistence. /cc @codepathreview @codepath
![customadapter1](https://cloud.githubusercontent.com/assets/2263278/7099013/010b2514-df9f-11e4-9933-56db9fe39988.gif)

**Comment by nidhi1608** [comment]
Varun,

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to schedule a short 5-10 minute phone conversation [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to include best number to reach you at? Look forward to chatting soon!

**Comment by varungu** [comment]
@nidhi1608 Thanks Nidhi, I selected a time interval for the phone conversation. Can you let me know the purpose of this conversation and who would be on the other side?

**Comment by nidhi1608** [comment]
Most likely you'll be talking with me. The purpose is to chat about your goals from this class and also provide insight into the overall class structure and logistics.
